name: Release to PyPI

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:
    name: Build dists
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: python -m pip install build
      - name: Build dists
        run: python -m build
      - name: Upload dists
        uses: actions/upload-artifact@v3
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error
          retention-days: 5

  pypi-publish:
    name: Upload release to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write  # Needed to upload dists to GitHub release
      id-token: write  # Needed for trusted publishing to PyPI

    steps:
      - name: Download dists
        uses: actions/download-artifact@v3
        with:
          name: "dist"
          path: "dist/"
      - name: Upload dists to GitHub Release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
